version: '3.8'
services:
  sqs:
    image: softwaremill/elasticmq-native:latest
    ports:
      - "9324:9324"
      - "9325:9325"
  s3:
    image: quay.io/minio/minio:latest
    command: ['server', '/data', '--console-address', ':9001']
    environment:
      - MINIO_ROOT_USER=admin
      - MINIO_ROOT_PASSWORD=adminpass
    ports:
      - '9000:9000'
      - '9001:9001'
